
#List of ranks
[[ranks]]
	tier = 0
	numAffixes = 0
	defaultColor = 16777215
	chance = 1.0
	growthFactor = 5
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 1
	numAffixes = 10
	defaultColor = 11053224
	chance = 0.0
	growthFactor = 7
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 2
	numAffixes = 10
	defaultColor = 11904578
	chance = 0.0
	growthFactor = 10
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 3
	numAffixes = 10
	defaultColor = 6750207
	chance = 0.0
	growthFactor = 12
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 4
	numAffixes = 10
	defaultColor = 13382655
	chance = 0.0
	growthFactor = 15
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 5
	numAffixes = 10
	defaultColor = 12326679
	chance = 0.0
	growthFactor = 18
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 6
	numAffixes = 10
	defaultColor = 16744192
	chance = 0.0
	growthFactor = 21
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 7
	numAffixes = 10
	defaultColor = 3329330
	chance = 0.0
	growthFactor = 9
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 8
	numAffixes = 10
	defaultColor = 13382296
	chance = 0.0
	growthFactor = 24
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 9
	numAffixes = 10
	defaultColor = 8900331
	chance = 0.0
	growthFactor = 27
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 10
	numAffixes = 10
	defaultColor = 12326679
	chance = 0.0
	growthFactor = 30
	effects = []
	presetAffixes = []

