
#List of diet effects
[[effects]]

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "all"
		above = 0.15
		below = 0.2999

[[effects]]

	[[effects.attributes]]
		name = "epicfight:stun_armor"
		operation = "multiply_total"
		amount = 0.03

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "all"
		above = 0.3
		below = 0.4999

[[effects]]

	[[effects.attributes]]
		name = "epicfight:stun_armor"
		operation = "multiply_total"
		amount = 0.06

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "all"
		above = 0.5
		below = 0.7499

[[effects]]

	[[effects.attributes]]
		name = "epicfight:stun_armor"
		operation = "multiply_total"
		amount = 0.08


	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "all"
		above = 0.75
		below = 0.8999

[[effects]]

	[[effects.attributes]]
		name = "epicfight:stun_armor"
		operation = "multiply_total"
		amount = 0.15

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "all"
		above = 0.9
		below = 1.0

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:water_breathing"
		power = 0

	[[effects.conditions]]
		groups = ["fruits"]
		match = "all"
		above = 0.6
		below = 1.0

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:speed"
		power = 0

	[[effects.conditions]]
		groups = ["sugars"]
		match = "all"
		above = 0.6
		below = 1.0

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:resistance"
		power = 0

	[[effects.conditions]]
		groups = ["grains"]
		match = "all"
		above = 0.6
		below = 1.0

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:strength"
		power = 0

	[[effects.conditions]]
		groups = ["proteins"]
		match = "all"
		above = 0.6
		below = 1.0

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:haste"
		power = 0

	[[effects.conditions]]
		groups = ["vegetables"]
		match = "all"
		above = 0.6
		below = 1.0

[[effects]]

	[[effects.status_effects]]
		name = "farmersdelight:nourishment"
		power = 0

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "all"
		above = 0.9
		below = 1.0


[[effects]]
	[[effects.attributes]]
		name = "minecraft:generic.armor_toughness"
		operation = "multiply_total"
		amount = 0.1

	[[effects.conditions]]
		groups = ["proteins", "vegetables", "grains"]
		match = "all"
		above = 0.5
		below = 0.5999

[[effects]]
	[[effects.attributes]]
		name = "minecraft:generic.armor_toughness"
		operation = "multiply_total"
		amount = 0.2

	[[effects.conditions]]
		groups = ["proteins", "vegetables", "grains"]
		match = "all"
		above = 0.6
		below = 0.6999

[[effects]]
	[[effects.attributes]]
		name = "minecraft:generic.armor_toughness"
		operation = "multiply_total"
		amount = 0.3

	[[effects.conditions]]
		groups = ["proteins", "vegetables", "grains"]
		match = "all"
		above = 0.7
		below = 0.7999

[[effects]]
	[[effects.attributes]]
		name = "minecraft:generic.armor_toughness"
		operation = "multiply_total"
		amount = 0.4

	[[effects.conditions]]
		groups = ["proteins", "vegetables", "grains"]
		match = "all"
		above = 0.8
		below = 0.8999
[[effects]]
	[[effects.attributes]]
		name = "minecraft:generic.armor_toughness"
		operation = "multiply_total"
		amount = 0.5

	[[effects.conditions]]
		groups = ["proteins", "vegetables", "grains"]
		match = "all"
		above = 0.9
		below = 1.0
