
[default_gamerule]
	doVanillaAttack = false
	globalStun = true
	keepSkills = true
	hasFallAnimation = true
	disapleEntityUI = false
	stiffComboAttacks = true
	#Range: 0 ~ 100
	weightPenalty = 80
	canSwitchCombat = true

[loot]
	#Range: -100 ~ 100
	skill_book_mob_drop_chance_modifier = -100
	#Range: -100 ~ 100
	skill_book_chest_drop_chance_modifier = -100

