
#A higher spawn weight will make the mob spawn more often.
#To prevent a certain mob from spawning, set its weight to 0.
["Mob Spawn Weights"]
	#Snail spawn weight
	#Range: 0 ~ 1000
	snailSpawnWeight = 2
	#Snake spawn weight
	#Range: 0 ~ 1000
	snakeSpawnWeight = 3
	#Coral Snake spawn weight
	#Range: 0 ~ 1000
	coralSnakeSpawnWeight = 3
	#Rattlesnake spawn weight
	#Range: 0 ~ 1000
	rattlesnakeSpawnWeight = 3
	#Bear spawn weight
	#Range: 0 ~ 1000
	bearSpawnWeight = 0
	#Deer spawn weight
	#Range: 0 ~ 1000
	deerSpawnWeight = 6
	#Firefly spawn weight
	#Range: 0 ~ 1000
	fireflySpawnWeight = 6
	#Bluejay spawn weight
	#Range: 0 ~ 1000
	bluejaySpawnWeight = 6
	#Canary spawn weight
	#Range: 0 ~ 1000
	canarySpawnWeight = 6
	#Cardinal spawn weight
	#Range: 0 ~ 1000
	cardinalSpawnWeight = 6
	#Robin spawn weight
	#Range: 0 ~ 1000
	robinSpawnWeight = 6
	#Butterfly spawn weight
	#Range: 0 ~ 1000
	butterflySpawnWeight = 4
	#Rabbit spawn weight in forest biomes
	#Range: 0 ~ 1000
	forestRabbitSpawnWeight = 4
	#Fox spawn weight in forest biomes
	#Range: 0 ~ 1000
	forestFoxSpawnWeight = 4
	#Rhino spawn weight
	#Range: 0 ~ 1000
	rhinoSpawnWeight = 10
	#Lion spawn weight
	#Range: 0 ~ 1000
	lionSpawnWeight = 10
	#Elephant spawn weight
	#Range: 0 ~ 1000
	elephantSpawnWeight = 0
	#Zebra spawn weight
	#Range: 0 ~ 1000
	zebraSpawnWeight = 7
	#Giraffe spawn weight
	#Range: 0 ~ 1000
	giraffeSpawnWeight = 7
	#Hippo spawn weight
	#Range: 0 ~ 1000
	hippoSpawnWeight = 15
	#Vulture spawn weight
	#Range: 0 ~ 1000
	vultureSpawnWeight = 10
	#Boar spawn weight
	#Range: 0 ~ 1000
	boarSpawnWeight = 10
	#Remove farm animals from savanna biomes (sheep, pig, chicken, cow)
	removeSavannaFarmAnimals = true

