
["level up exp cost multiply"]
	xp_multiply = 0.5

["imbue sword spell cooldown multiply"]
	cooldown_multiply = 3

["Attack animations that will definitely trigger a critical hit, player only"]
	animations = ["epicfight:biped/combat/uchigatana_sheath_auto", "epicfight:biped/combat/uchigatana_sheath_dash", "epicfight:biped/combat/uchigatana_sheath_airslash", "epicfight:biped/skill/battojutsu_dash", "epicfight:biped/skill/battojutsu", "epicfight:biped/skill/grasping_spire_second", "falchionmoveset:biped/falchion/falchion_forward", "star:biped/new/yamato/skill/yamato_power0_2", "star:biped/new/yamato/skill/yamato_strike1", "star:biped/new/yamato/skill/yamato_counter_2", "star:biped/new/yamato/skill/yamato_power3", "star:biped/new/yamato/skill/yamato_power3_repeat", "star:biped/new/yamato/skill/yamato_power3_finish", "wom:biped/combat/katana_sheathed_dash", "wom:biped/skill/katana_fatal_draw", "wom:biped/skill/katana_fatal_draw_dash", "wom:biped/skill/katana_fatal_draw_second"]

["Attribute multiply"]
	#Range: 0.0 ~ 1000.0
	"Melee damage bonus per point of attribute" = 0.006
	#Range: 0.0 ~ 100.0
	"Block rate bonus per point of attribute, will always be less than 100 in total" = 0.75
	#Range: 0.0 ~ 1000.0
	"Max health bonus per point of attribute" = 1
	#Range: 0.0 ~ 1000.0
	"Burden bonus per point of attribute" = 1.0
	#Range: 0.0 ~ 1000.0
	"Movement speed bonus per point of attribute" = 3.0E-4
	#Range: 0.0 ~ 1000.0
	"Attack speed bonus per point of attribute" = 0.002
	#Range: 0.0 ~ 100.0
	"Crit damage bonus per point of attribute" = 0.01
	#Range: 0.0 ~ 1000.0
	"Spell damage bonus per point of attribute" = 0.01
	#Range: 0.0 ~ 1000.0
	"Spell cooldown bonus per point of attribute" = 0.01
	#Range: 0.0 ~ 1000.0
	"Spell cast time bonus per point of attribute" = 0.01
	#Range: 0.0 ~ 10.0
	"Crit chance bonus per point of attribute" = 0.01
	#Range: 0.0 ~ 1000.0
	"Arrow Damage bonus per point of attribute" = 0.005
	#Range: 0.0 ~ 1000.0
	"Max mana bonus per point of attribute" = 3.0
	#Range: 0.0 ~ 1000.0
	"Spell resist bonus per point of attribute" = 0.015
	#Range: 0.0 ~ 1000.0
	"Max stamina bonus per point of attribute" = 0.2
	#Range: 0.0 ~ 1000.0
	"Stun armor bonus per point of attribute" = 0.1
	#Range: 0.0 ~ 1000.0
	"Luck bonus per point of attribute" = 0.2

["disable right click using imbue sword"]
	"disable using imbue sword" = true

["use item to level up"]
	"use item to level up" = true
	"level up item" = "stellarisdlc:attribute_scrap"

["base value of crit damgage"]
	#Range: 0.0 ~ 1000.0
	"base value of crit damga multiply" = 1.2

